services:
  mongo:
    image: mongo:6
    restart: always
    container_name: mongo
    command: ["--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - /app/mongo:/data/db
  back-end:
    build: ../back-end
    restart: always
    hostname: backend
    environment:
      NODE_ENV: "production"
      DATABASE_URL: "${DATABASE_URL}"
      JWT_SECRET: "${JWT_SECRET}"
      ORIGIN: "${DOMAIN}"
    depends_on:
        - mongo
    volumes:    
      - /app/files:/app/files      
      - /var/run/docker.sock:/var/run/docker.sock
    
  front-end:
    hostname: frontend
    restart: always
    build:
      context: ../front-end
      args:
        VITE_API_URL: "${DOMAIN}/api"
        VITE_SOCKET_URL: "${DOMAIN}"
    depends_on:
        - back-end
  nginx:    
      image: nginx:stable-alpine
      restart: always
      ports:
        - "443:443"                
      volumes:          
        - ./nginx/config:/etc/nginx/conf.d/
        - ./nginx/logs:/var/log/nginx/ 
        - ./nginx/keys:/etc/nginx/certs/
      depends_on:
        - front-end
        - back-end
        - mongo