services:
  apache:
    image: httpd:2.4 
    ports:
        - "80:80"  
    volumes:
      - ../AA:/usr/local/apache2/htdocs/AA

  mongo:
    image: mongo:6
    hostname: mongo
    command: ["--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - ./mongo-data:/data/db
  back-end:
    build: ../back-end
    hostname: backend
    environment:
      NODE_ENV: "production"
      DATABASE_URL: "mongodb://mongo:27017/phpeditor"
      SECRET: "yout-secret"
    depends_on:
        - mongo
  front-end:
    hostname: frontend
    build:
      context: ../front-end
      args:
        VITE_API_URL: http://phpeditor.bruno.s.c.vms.ufsc.br:8080/api
    depends_on:
        - back-end
  nginx:    
      image: nginx:stable-alpine
      restart: always
      ports:
        - "8080:8080"                
      volumes:          
        - ./nginx/config:/etc/nginx/conf.d/
        - ./nginx/logs:/var/log/nginx/ 

      depends_on:
        - front-end
        - back-end
        - mongo
  